const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
const script = fs.readFileSync("script.js", "utf8");
const nav = html.match(/<nav class="section-nav"[\s\S]*?<\/nav>/)?.[0] || "";
const maskedCard = html.match(/<article class="project-card project-masked[\s\S]*?<\/article>/)?.[0] || "";
const kimodoCard = html.match(/<article class="project-card project-kimodo[\s\S]*?<\/article>/)?.[0] || "";
const gpcCard = html.match(/<article class="project-card project-gpc[\s\S]*?<\/article>/)?.[0] || "";

assert.match(html, /<div class="hero-heading reveal">[\s\S]*<h1 id="hero-title">Learning motion for <em>System 1 control\.<\/em>/, "the thesis should name the reflex-control focus");
assert.match(html, /<h2 id="focus-title">Three systems,<br \/><em>a common vision\.<\/em><\/h2>/, "selected work should frame the cards around a shared vision");
assert.match(css, /\.hero-heading\s*\{[^}]*grid-column:\s*1 \/ -1/, "the thesis row should span both hero columns");
assert.match(css, /\.hero-heading h1\s*\{[^}]*max-width:\s*none/, "the thesis should not be constrained to the lower copy column");
assert.match(css, /\.hero-copy\s*\{[^}]*grid-column:\s*1/, "the lower copy should stay in the left hero column");
assert.match(css, /\.portrait-card\s*\{[^}]*grid-column:\s*2/, "the portrait should stay in the right hero column");
assert.match(css, /\.section-pad\s*\{[^}]*padding: clamp\(4rem, 7vw, 6\.5rem\)/, "section spacing should keep breathing room without excessive margins");
assert.match(css, /\.project-list\s*\{[^}]*margin-top: clamp\(2rem, 4\.5vw, 4rem\)/, "featured work should arrive closer to its heading");
assert.match(css, /\.publication-intro\s*\{[^}]*margin-top: clamp\(2rem, 4vw, 3\.5rem\)/, "publication intro spacing should stay compact");
assert.ok(nav.indexOf('href="#about"') < nav.indexOf('href="#publications"'), "sidebar navigation should follow the page flow");
assert.doesNotMatch(html, /class="hero-thread"/, "the hero should not contain a current-thread block");
assert.doesNotMatch(html, /I’m interested in the space between a model that can move/, "the About section should keep only the focused research statement");
assert.match(css, /\.about-copy\s*\{[^}]*grid-column:\s*1 \/ -1/, "the focused About statement should span the full width");
assert.match(html, /shared framework for humanoid simulation and control/, "the open-source note should explain ProtoMotions' practical role");
assert.match(kimodoCard, /Kinematic model \/ synthetic data/, "Kimodo should be framed as a kinematic synthetic-data model");
assert.match(kimodoCard, /Synthetic data/, "Kimodo should surface its synthetic-data use");
assert.match(kimodoCard, /autoplay muted loop playsinline[^>]*poster="assets\/kimodo-poster\.jpg"/, "Kimodo should autoplay its local video without controls");
assert.match(kimodoCard, /assets\/kimodo\.mp4/, "Kimodo should use the downloaded local video");
assert.doesNotMatch(kimodoCard, /g1_text_loco2\.mp4/, "Kimodo should replace the old remote video");
assert.doesNotMatch(kimodoCard, /Near-short horizon|real-time decisions|Short-horizon control/, "Kimodo should not be framed as short-horizon control");
assert.match(maskedCard, /Physics-based robotics \/ zero-shot guidance/, "MaskedMimic should foreground physics-based robotics and zero-shot guidance");
assert.match(maskedCard, /Motion inpainting/, "MaskedMimic should surface its motion-inpainting method");
assert.match(maskedCard, /physics-based controller/, "MaskedMimic should be distinguished from kinematic animation");
assert.match(maskedCard, /autoplay muted loop playsinline[^>]*poster="assets\/maskedmimic-poster\.jpg"/, "MaskedMimic should autoplay its local video without controls");
assert.match(maskedCard, /assets\/maskedmimic\.mp4/, "MaskedMimic should use the downloaded local video");
assert.match(gpcCard, /Physics-based robotics \/ reusable motion prior/, "GPC should foreground physics-based robotics and reusable motion priors");
assert.doesNotMatch(gpcCard, /Pretraining \/ control as a prior/, "GPC should not be framed as a generic pretraining/control card");
assert.match(gpcCard, /physics simulation and robotics/, "GPC should be distinguished from kinematic animation");
assert.match(gpcCard, /autoplay muted loop playsinline[^>]*poster="assets\/gpc-poster\.jpg"/, "GPC should autoplay its local video without controls");
assert.match(gpcCard, /assets\/gpc\.mp4/, "GPC should use the downloaded local video");
assert.doesNotMatch(html, /youtube-nocookie\.com|platform\.twitter\.com\/widgets\.js/, "the cards should not depend on external video embeds");
assert.doesNotMatch(html, /Video source/, "the cards should keep only useful project-page links");

const ledeIndex = html.indexOf('class="hero-lede"');
const profileIndex = html.indexOf('class="profile-links"');
const openSourceIndex = html.indexOf('class="open-source-note"');
assert.ok(ledeIndex >= 0 && profileIndex > ledeIndex && openSourceIndex > profileIndex, "about links should sit between the hero lede and ProtoMotions note");
assert.match(html, /<nav class="profile-links" aria-label="About Chen Tessler">/, "about links should have a named navigation group");
assert.match(html, /href="https:\/\/scholar\.google\.com\/citations\?user=7eLKa3IAAAAJ&hl=en&oi=ao"[^>]*>Scholar/, "Scholar link should be present");
assert.match(html, /href="https:\/\/x\.com\/ChenTessler"[^>]*>X/, "X link should be present");
assert.match(html, /href="https:\/\/www\.linkedin\.com\/in\/chentessler\/"[^>]*>LinkedIn \/ CV/, "LinkedIn and CV link should be present");
assert.equal((html.match(/class="profile-link"/g) || []).length, 3, "the about rail should contain exactly three links");
assert.match(html, /class="open-source-impact"[^>]*aria-label="ProtoMotions community stars"/, "ProtoMotions should expose a community impact link");
assert.match(html, /data-github-stars[^>]*data-github-stars-fallback="2\.1k">2\.1k/, "the star count should have a visible fallback before the API responds");
assert.match(html, /class="open-source-impact-label">community stars/, "the impact readout should name what it measures");
assert.match(css, /\.profile-links\s*\{/, "about links should have a dedicated layout rule");
assert.match(css, /\.profile-link\s*\{/, "about links should have a dedicated link rule");
assert.match(css, /\.open-source-impact\s*\{/, "the community signal should have a dedicated visual treatment");
assert.match(css, /\.open-source-note\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto[^}]*grid-template-rows:\s*auto\s+auto/, "desktop ProtoMotions content should use a two-column, two-row stack");
assert.match(css, /\.open-source-copy\s*\{[^}]*grid-row:\s*1\s*\/\s*span\s*2/, "desktop ProtoMotions copy should span both impact rows");
assert.match(css, /\.open-source-impact\s*\{[^}]*grid-column:\s*2[^}]*grid-row:\s*1/, "desktop stars should sit above the framework link");
assert.match(css, /\.open-source-note > a:not\(\.open-source-impact\)\s*\{[^}]*grid-column:\s*2[^}]*grid-row:\s*2/, "desktop framework link should sit below the stars");
assert.match(script, /api\.github\.com\/repos\/NVlabs\/ProtoMotions/, "the page should query the ProtoMotions repository");
assert.match(script, /stargazers_count/, "the page should read GitHub's star-count field");
assert.match(script, /Intl\.NumberFormat/, "the live star count should be formatted for display");
assert.match(script, /catch\(\(\) =>/, "the star count should have a graceful API failure path");
assert.match(script, /const fallback = value\.dataset\.githubStarsFallback \|\| value\.textContent/, "the star count should retain its static fallback");
assert.match(script, /value\.textContent = fallback/, "API failure should preserve the visible fallback count");

console.log("hero layout checks passed");
